export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{border :'1px solid black',height:'5rem'}}>
          header
        </header>
        {children}
        <footer style={{border :'1px solid black',height:'5rem'}}>
          footer
        </footer>
        </body>
    </html>
  )
}
